#!/usr/bin/env python3
"""Generate docker-compose.agentbox.yml from agent registry."""

import yaml
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
AGENTS_DIR = REPO_ROOT / "platform" / "agentbox" / "agents"
OUTPUT = REPO_ROOT / "deploy" / "compose" / "prod" / "docker-compose.agentbox.yml"

compose = {
    "networks": {
        "internal": {"external": True, "name": "hill90_internal"},
    },
    "volumes": {},
    "services": {},
}

for agent_dir in sorted(AGENTS_DIR.iterdir()):
    if not agent_dir.is_dir():
        continue
    config_file = agent_dir / "agent.yml"
    if not config_file.exists():
        continue

    config = yaml.safe_load(config_file.read_text())
    agent_id = config["id"]
    res = config.get("resources", {})

    vol_workspace = f"agentbox-{agent_id}-workspace"
    vol_logs = f"agentbox-{agent_id}-logs"
    vol_data = f"agentbox-{agent_id}-data"
    compose["volumes"][vol_workspace] = {}
    compose["volumes"][vol_logs] = {}
    compose["volumes"][vol_data] = {}

    # Absolute paths for bind mounts (repo-root anchored)
    agent_config_path = str(agent_dir / "agent.yml")
    soul_path = str(agent_dir / "SOUL.md")
    rules_path = str(agent_dir / "RULES.md")

    service = {
        "image": "hill90/agentbox:${VERSION:-latest}",
        "container_name": f"agentbox-{agent_id}",
        "restart": "unless-stopped",
        "networks": ["internal"],
        "volumes": [
            f"{agent_config_path}:/etc/agentbox/agent.yml:ro",
            f"{soul_path}:/etc/agentbox/SOUL.md:ro",
            f"{rules_path}:/etc/agentbox/RULES.md:ro",
            f"{vol_workspace}:/workspace",
            f"{vol_logs}:/var/log/agentbox",
            f"{vol_data}:/data",
        ],
        "environment": [
            "ENVIRONMENT=production",
            f"AGENT_ID={agent_id}",
            "AGENT_CONFIG=/etc/agentbox/agent.yml",
            f"OTEL_SERVICE_NAME=agentbox-{agent_id}",
            "OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318",
            "OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf",
            "OTEL_TRACES_EXPORTER=otlp",
            "OTEL_METRICS_EXPORTER=none",
            "OTEL_LOGS_EXPORTER=none",
        ],
        # Non-swarm resource limits (docker compose v2 compatible)
        "cpus": float(res.get("cpus", "1.0")),
        "mem_limit": res.get("mem_limit", "1g"),
        "pids_limit": int(res.get("pids_limit", 200)),
        "healthcheck": {
            "test": ["CMD", "curl", "-sf", "http://localhost:8054/health"],
            "interval": "30s",
            "timeout": "10s",
            "retries": 3,
        },
        "labels": ["traefik.enable=false"],
    }
    compose["services"][f"agentbox-{agent_id}"] = service

header = "# AUTO-GENERATED by scripts/agentbox-compose-gen.py — do not edit\n"
header += "# Regenerate: python scripts/agentbox-compose-gen.py\n\n"
OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text(header + yaml.dump(compose, default_flow_style=False, sort_keys=False))
print(f"Generated {OUTPUT} with {len(compose['services'])} agent(s)")
