#!/usr/bin/env python3
"""Validate that all stateful compose volumes have explicit name: fields.

Prevents volume namespace drift when compose project names change.
Uses 'docker compose config --format json' for reliable YAML parsing
via the compose binary, then checks the JSON output with stdlib json.

Exit codes:
    0 — all volumes have explicit names
    1 — at least one volume is missing an explicit name
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# Stateful compose files that must have explicit volume names.
# Excluded: docker-compose.agentbox.yml — ephemeral workspace volumes
# generated by agentbox-compose-gen.py; not subject to this invariant.
TARGET_FILES = [
    "deploy/compose/prod/docker-compose.db.yml",
    "deploy/compose/prod/docker-compose.infra.yml",
    "deploy/compose/prod/docker-compose.minio.yml",
    "deploy/compose/prod/docker-compose.observability.yml",
]


def check_file(rel_path: str) -> list[str]:
    """Return list of error messages for volumes missing explicit name:."""
    full_path = ROOT / rel_path
    if not full_path.exists():
        return [f"{rel_path}: file not found"]

    try:
        result = subprocess.run(
            ["docker", "compose", "-f", str(full_path), "config", "--format", "json"],
            capture_output=True,
            text=True,
            check=True,
            cwd=ROOT,
        )
    except FileNotFoundError:
        # docker compose not available — fall back to raw YAML key scan
        return check_file_fallback(rel_path)
    except subprocess.CalledProcessError as exc:
        return [f"{rel_path}: docker compose config failed: {exc.stderr.strip()}"]

    try:
        config = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        return [f"{rel_path}: failed to parse JSON output: {exc}"]

    errors: list[str] = []
    volumes = config.get("volumes", {})
    for key, vol_config in volumes.items():
        if not isinstance(vol_config, dict):
            errors.append(f"{rel_path}: volume '{key}' has no explicit name: field")
            continue
        name = vol_config.get("name")
        if not name:
            errors.append(f"{rel_path}: volume '{key}' has no explicit name: field")

    return errors


def check_file_fallback(rel_path: str) -> list[str]:
    """Fallback when docker compose is not available — grep for name: under volumes."""
    import re

    full_path = ROOT / rel_path
    content = full_path.read_text(encoding="utf-8")
    errors: list[str] = []

    # Find the top-level volumes: block and check each volume key for a name: sub-key
    in_volumes = False
    current_key: str | None = None
    has_name = False

    for line in content.splitlines():
        stripped = line.strip()

        # Detect top-level volumes: section (no indentation)
        if re.match(r"^volumes:\s*$", line):
            in_volumes = True
            continue

        # Another top-level section ends volumes
        if in_volumes and re.match(r"^\S", line) and not line.startswith(" "):
            if current_key and not has_name:
                errors.append(f"{rel_path}: volume '{current_key}' has no explicit name: field")
            in_volumes = False
            current_key = None
            continue

        if not in_volumes:
            continue

        # Volume key (2-space indent, no further indent)
        key_match = re.match(r"^  (\S+):\s*$", line)
        if key_match:
            if current_key and not has_name:
                errors.append(f"{rel_path}: volume '{current_key}' has no explicit name: field")
            current_key = key_match.group(1)
            has_name = False
            continue

        # name: sub-key under a volume (4-space indent)
        if current_key and re.match(r"^    name:\s+\S", line):
            has_name = True

    # Handle last volume key
    if in_volumes and current_key and not has_name:
        errors.append(f"{rel_path}: volume '{current_key}' has no explicit name: field")

    return errors


def main() -> int:
    all_errors: list[str] = []
    for f in TARGET_FILES:
        all_errors.extend(check_file(f))

    if all_errors:
        print("Volume naming violations found:")
        for err in all_errors:
            print(f"  - {err}")
        return 1

    print(f"All {len(TARGET_FILES)} compose files have explicit volume names.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
