name: Manual Deploy Auth (Prod)

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-service.yml
    with:
      service: auth
    secrets: inherit
